name: halite
dependencies:
  - numpy
  - matplotlib
  - pillow
  - pyyaml
  - pathlib
  - pytest
  - requests
  - idna
  - flake8
  - tqdm
  - conda-forge::kaggle
  - conda-forge::kaggle_environments
  - conda-forge::gym