agent:
  dir: "src/agent"
  submission_file_name: "submission_agent.py"
replay:
  mode: "html"
  width: 800
  height: 600
submit:
  export_dir: "build" # If this is changed, gitignore must be modified
  export_file_name: "export.py"
  build_blacklist: ["src/agent/learning/train"]
board:
  max_cell_halite: 500
  dims: [9, 21, 21]
  size: 21
learn:
  batch_size: 250
  num_train_episodes: 10000
  gamma: 0.999
  eps_start: 0.9
  eps_end: 0.05
  eps_decay: 200
  target_update: 10
  replay_memory_capacity: 10000
  num_additional_vals: 5
  models:
    save_dir: "models"
    ship_agent_file: "ship_agent.pt"
    shipyard_agent_file: "shipyard_agent.pt"
gym:
  version: 0.1